export const homeRoutes=[
    {
        name:"Home",
        path:"/"
    },
    {
        name:"About Us",
        path:"/about"
    },
    {
        name:"Services",
        path:"/services"
    },
    {
        name:"Pricing",
        path:"/pricing"
    },
    {
        name:"Contact",
        path:"/contact"
    },
    {
        name:"Contact",
        path:"/contact"
    },
    {
        name:"Map",
        path:"/map"
    },
]